#=======================================#
#		     Npc Properties             
#=======================================#

#=======================================#
#      The characteristics of NPC
#=======================================#
# State of monsters and NPCS
# 1 - Show level and aggressive of the monster
# 2 - Maximum range mobs can randomly go from spawn point
ShowNpcLevel = True
MaxDriftRange = 120

# Teleport sem custo de adena
# Default = False
FreeTeleporting = False
FreeTeleportingMinLvL = 1
FreeTeleportingMaxLvL = 99

#Noblesse teleport(via nobless gatepass) free
# Default = FALSE
NoblePassFreeTp = False
NoblePassFreeTpMinLvL = 1
NoblePassFreeTpMaxLvL = 99

# The minimum and maximum variable delay, in seconds, for the animation of NPCS
# Warning! MinNPCAnimation < MaxNPCAnimation.
# Move NPC
MinNPCAnimation = 10
MaxNPCAnimation = 20
MinMonsterAnimation = 5
MaxMonsterAnimation = 20
MinNPCWalkAnimation = 10
MaxNPCWalkAnimation = 20

# Movement speed for Strider and Wyvern
WyvernSpeed = 100
StriderSpeed = 80

# Monsters on the peaceful territory aggressiveness
# Invulnerability monsters
# Walking NPC
AltMobAggroInPeaceZone = True
AltAttackableNpcs = False
AllowPetWalker = True

# Alchemist Mixing Urn temp fail
UrnTempFail = 10

#=======================================#
#		Additional NPC services
#=======================================#
# Pet rental service for players
AllowRentPet = False

# Service of the Wyvern!!!!
AllowWyvernUpgrader = False

# Alt Pet Managers Crystal Count
# default = 25
ManagerCrystalCount = 25

#=======================================#
#       Class Master Configs Npc
#===============================================================#
#                    Class Master (Gerenciador de Classes)
#===============================================================#
# Ativa o sistema do Class Master no servidor
ClassMaster = True

# Spawna os NPCs Class Master (Mr. Cat / Gatos) nas cidades
SpawnClassMaster = True

# Permite trocar de classe alternativamente ao atingir os niveis 20, 40 e 76
AltClassMaster = True
ClassMasterPopupWindow = True

# Permite ao Class Master enviar mensagens de parabens no chat
AllowDialogClassMater = True

# Permite trocar para qualquer classe dentro da arvore de classes
ClassMasterEntireTree = False

# Permite atualizar Hatchling para Strider no Class Master
ClassMasterUpdateStrider = False

# Tabela de Requisitos e Recompensas:
# Sintaxe: ocupacao;[item_exigido(qtd)],...;[item_recompensa(qtd)],...;ocupacao...
# Exemplo gratuito: ConfigClassMaster = 1;[];[];2;[];[];3;[];[]
# 1st: 100k Adena | 2nd: 1kk Adena | 3rd: 10kk Adena + 1kk Ancient Adena (Recompensa: 1 Book of Giants)
ConfigClassMaster = 1;[57(100000)];[];2;[57(1000000)];[];3;[57(10000000)],[5575(1000000)];[6622(1)]

#=======================================#
#           Adjusting bosses
#=======================================#
# Overlay in effect paralyze the player if its level of +/-9 than the level boss
# false- use restriction levels
# true - do not use restriction
DisableRaidBossFossilization = False

# The maximum level to which the effect is applied boss Raid Curse
# Works when DisableRaidBossFossilization = false
MaxLevelRaidBossCurse = 87

# Instantly update a database of information on the status of the boss after his assassination
# Use this option with caution.
ForceUpdateRaidBossOnDB = False

# Remove o player da area setada como noRestart na zona.xml se ele ficar off nessa area por mais tempo que setado aqui
# Tempo em MINUTOS
NoRestartKickTime = 5

# If True, Lethal Protected Mobs (in LethalProtectedMobs property) cannot receive Lethal shot
AllowLethalProtectionMobs = False

# es. : LethalProtectedMobs = 35062,21436
# 35062 = CTFFlag
LethalProtectedMobs = 35062