-- Portado de tools/sql/char_templates.sql (somente estrutura; dados estaticos ficam fora do Flyway)
CREATE TABLE IF NOT EXISTS `char_templates` (
  `ClassId` int(11) NOT NULL DEFAULT 0,
  `ClassName` varchar(20) NOT NULL DEFAULT '',
  `RaceId` int(1) NOT NULL DEFAULT 0,
  `parent` tinyint(3) unsigned DEFAULT 255,
  `level` tinyint(3) unsigned DEFAULT 0,
  `STR` int(2) NOT NULL DEFAULT 0,
  `CON` int(2) NOT NULL DEFAULT 0,
  `DEX` int(2) NOT NULL DEFAULT 0,
  `_INT` int(2) NOT NULL DEFAULT 0,
  `WIT` int(2) NOT NULL DEFAULT 0,
  `MEN` int(2) NOT NULL DEFAULT 0,
  `P_ATK` int(3) NOT NULL DEFAULT 0,
  `P_DEF` int(3) NOT NULL DEFAULT 0,
  `M_ATK` int(3) NOT NULL DEFAULT 0,
  `M_DEF` int(2) NOT NULL DEFAULT 0,
  `P_SPD` int(3) NOT NULL DEFAULT 0,
  `M_SPD` int(3) NOT NULL DEFAULT 0,
  `ACC` int(3) NOT NULL DEFAULT 0,
  `CRITICAL` int(3) NOT NULL DEFAULT 0,
  `EVASION` int(3) NOT NULL DEFAULT 0,
  `RUN_SPD` int(3) NOT NULL DEFAULT 0,
  `WALK_SPD` int(3) NOT NULL DEFAULT 0,
  `x` int(9) NOT NULL DEFAULT 0,
  `y` int(9) NOT NULL DEFAULT 0,
  `z` int(9) NOT NULL DEFAULT 0,
  `canCraft` int(1) NOT NULL DEFAULT 0,
  `M_UNK1` decimal(4,2) NOT NULL DEFAULT 0.00,
  `M_UNK2` decimal(8,6) NOT NULL DEFAULT 0.000000,
  `M_COL_R` decimal(3,1) NOT NULL DEFAULT 0.0,
  `M_COL_H` decimal(4,1) NOT NULL DEFAULT 0.0,
  `F_UNK1` decimal(4,2) NOT NULL DEFAULT 0.00,
  `F_UNK2` decimal(8,6) NOT NULL DEFAULT 0.000000,
  `F_COL_R` decimal(3,1) NOT NULL DEFAULT 0.0,
  `F_COL_H` decimal(4,1) NOT NULL DEFAULT 0.0,
  `items1` int(4) NOT NULL DEFAULT 0,
  `items2` int(4) NOT NULL DEFAULT 0,
  `items3` int(4) NOT NULL DEFAULT 0,
  `items4` int(4) NOT NULL DEFAULT 0,
  `items5` int(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ClassId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AVG_ROW_LENGTH=150;

